import Head from 'next/head'
import Footer from '../components/Footer/Footer';
import Images from '../components/Images/Images'
import Topbar from '../components/Topbar/Topbar';


export default function Home({ ImageUrls }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topbar />
      <main>
        <Images ImageUrls={ImageUrls} />
      </main>

      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const response = await (await fetch('https://www.reddit.com/r/images/new.json?limit=30')).json();
  const ImageUrls = response.data.children.map((child)=>{
    return child.data.thumbnail
  })
  return {
    props: { ImageUrls: ImageUrls },
  }
}
